name: Test-Final
on:
  workflow_dispatch:      # Pour pouvoir le lancer à la main
  schedule:
    - cron: '0 7 * * *'  # S'exécute automatiquement tous les jours à 8h00 UTC
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lancer le robot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          pip install requests
          python bot.py
          
